name: Slither Analysis action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          fail-on: none
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
          target: contracts/

      - name: Create/update checklist as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
            REPORT: ${{ steps.slither.outputs.stdout }}
            
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const MAX_LENGTH = 65536;
            const truncatedReport = process.env.REPORT.length > MAX_LENGTH ? process.env.REPORT.substring(0, MAX_LENGTH) + '... (Report truncated due to length)' : process.env.REPORT;
            const body = `${header}\n${truncatedReport}`;
            await script({ github, context, header, body });
